### ISSUE TITLE
Timeline for your pull request to gskleres/nqmod-vs2008?

### ISSUE THREAD

**Issue by ScrambledEggsOnToast** [DelnarErsike/nqmod-vs2008#1]
Great work with all of the cleaning and optimisation you're doing. Do you know how soon you think you'll be ready to submit a pull request to gskleres/nqmod-vs2008 for your modifications? I only ask because I have a few (hopefully uncontroversial) changes that I've been working on over in [ScrambledEggsOnToast/nqmod-vs2008](https://github.com/ScrambledEggsOnToast/nqmod-vs2008), and I'm wondering whether I should wait for your changes to go in before I submit my own.

**Comment by DelnarErsike** [comment]
We're unlikely to make directly competing changes, though some of your changes may become redundant once all of my changes are applied (eg. the change that puts cities on production focus by default would be redundant if food is also processed from population on growth OR if new population is automatically assigned disregarding food yield and reassigned to consider food yield after the turn is complete). Merging code should therefore not be an issue, even with my massive amounts of Warning fixes coming up, so feel free to continue coding as you wish.

However, I don't know if it's a good idea to fork my repo over fruitstrike's: after I'm done porting changes and my pull request is accepted by fruitstrike, I expect to become less active with my NQMod repo, to the point where I may fall behind on commits from fruitstrike's repo. If you fork my repo, you'll be forced to merge commits to fruitstrike's repo at my pace at least, while if you fork from fruitstrike's repo, you can merge his commits without worrying about me merging them into my repo beforehand.

**Comment by ScrambledEggsOnToast** [comment]
Ok, sounds good. The reason I've forked yours is really just for the convenience of your added missing files and _Defines.h setup. Once you become less active, I'll switch over to a fork of fruitstrike's.

Edit: Actually, I think I will move over now. I've done most of the changes I would like, so I no longer really need that convenience.
